services:
  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rjm.rule=Host(`rjm.ie`)"
      - "traefik.http.services.rjm.loadbalancer.server.port=80"
      - "traefik.http.routers.rjm.entrypoints=websecure"
      - "external-service=true"
    build: .
    networks:
      - traefik-external
    container_name: "rjm-site"
    restart: always

networks:
  traefik-external:
    external: true